program: 
	g++ ./_definitions/*.cpp -o program

# main.o: ./_definitions/main.cpp ./_definitions/shell.cpp dir.o
# 	g++ -c std=c++11 ./_definitions/main.cpp ./_definitions/shell.cpp dir.o -o program

# mem.o:./_definitions/mem.cpp
# 	g++ -c ./_definitions/mem.cpp -o mem.o

# dir.o: ./_definitions/directory.cpp ./_definitions/folder.cpp ./_definitions/file.cpp
# 	g++  ./_definitions/directory.cpp ./_definitions/folder.cpp ./_definitions/file.cpp -o program

